import { createHash, randomUUID, timingSafeEqual } from "crypto";
import type { NextFunction, Request, RequestHandler, Response } from "express";
import type { RuntimeConfig } from "../config";
import type { LookupService, Scenario, ValidatedLookupCommand } from "../domain/contracts";
/** Writes a standardized safe failure response. */
export function safeError(res: Response, status: number, code: string, message: string, retryable = false): void { res.status(status).json({ error: { code, message, retryable }, meta: { correlationId: res.locals.correlationId } }); }
/** Attaches a caller-safe opaque correlation id to every lookup response. */
export const correlationGate: RequestHandler = (_req, res, next) => { const supplied = _req.header("x-correlation-id"); res.locals.correlationId = supplied && /^[a-zA-Z0-9-]{8,100}$/.test(supplied) ? supplied : randomUUID(); res.setHeader("X-Correlation-ID", res.locals.correlationId); next(); };
/** Rejects unsupported media before body or service processing. */
export const mediaGate: RequestHandler = (req, res, next) => { if (!req.is("application/json") || !req.accepts("application/json")) return safeError(res, 400, "INVALID_REQUEST", "Review the lookup request and try again."); next(); };
/** Validates client keys using timing-safe comparison and never stores the raw key. */
export function authorizeApiKey(config: RuntimeConfig): RequestHandler { return (req, res, next) => { const raw = req.header("x-api-key"); if (!raw) return safeError(res, 401, "MISSING_API_KEY", "Provide an authorized API key."); const valid = config.apiKeys.some((candidate) => { const a = Buffer.from(candidate); const b = Buffer.from(raw); return a.length === b.length && timingSafeEqual(a, b); }); if (!valid) return safeError(res, 403, "UNAUTHORIZED_API_KEY", "Verify authorized access."); res.locals.apiKeyIdHash = createHash("sha256").update(raw).digest("hex"); next(); }; }
/** Uses a bounded in-process development limiter behind the production limiter interface. */
export function enforceRateLimit(limit: number): RequestHandler { const counts = new Map<string, number>(); return (_req, res, next) => { const key = res.locals.apiKeyIdHash as string; const nextCount = (counts.get(key) ?? 0) + 1; counts.set(key, nextCount); if (nextCount > limit) { res.setHeader("Retry-After", "60"); return safeError(res, 429, "RATE_LIMITED", "Wait before a new lookup.", true); } next(); }; }
/** Produces a new closed-schema lookup command and discards the raw body reference. */
export function validateLookup(_service: LookupService): RequestHandler { return (req, res, next) => { const body: unknown = req.body; if (!body || typeof body !== "object" || Array.isArray(body)) return safeError(res, 400, "INVALID_REQUEST", "Review the lookup request and try again."); const value = body as Record<string, unknown>; const keys = Object.keys(value); if (keys.length !== 3 || !keys.every((key) => ["VIN", "PARAM_1", "SOURCE"].includes(key))) return safeError(res, 400, "INVALID_REQUEST", "Review the lookup request and try again."); const vin = typeof value.VIN === "string" ? value.VIN.trim() : ""; const scenario = value.PARAM_1; if (!vin || (scenario !== "RO_OPEN" && scenario !== "RO_CLOSE") || value.SOURCE !== "COMPASS") return safeError(res, 400, "INVALID_REQUEST", "Review the lookup request and try again."); res.locals.command = { vin, scenario: scenario as Scenario, source: "COMPASS", correlationId: res.locals.correlationId, apiKeyIdHash: res.locals.apiKeyIdHash } satisfies ValidatedLookupCommand; next(); }; }
