import type React from "react";
import { useReducer } from "react";
import { lookup } from "../api/rojClient";
import { initialLookupState, lookupReducer, validateForm } from "../state/lookupReducer";
import type { ApiFailure, ApiSuccess } from "../types";
/** Renders the accessible, in-memory-only operator lookup form. */
export interface LookupViewProps { onResolved: (response: { status: number; body: ApiSuccess | ApiFailure }) => void; }
/** Collects one validated lookup request and clears the credential after the response settles. */
export const LookupView: React.FC<LookupViewProps> = ({ onResolved }) => { const [state, dispatch] = useReducer(lookupReducer, initialLookupState); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const errors = validateForm(state.form); if (Object.keys(errors).length) { dispatch({ type: "VALIDATE" }); return; } dispatch({ type: "SUBMIT" }); try { onResolved(await lookup(state.form.vin, state.form.scenario, state.form.apiKey)); } catch { onResolved({ status: 503, body: { error: { code: "SERVICE_UNAVAILABLE", message: "Try a new lookup later.", retryable: true }, meta: { correlationId: "unavailable" } } }); } finally { dispatch({ type: "SETTLED" }); } };
 return <main className="shell"><header><p className="kicker">CSMS / COMPASS</p><h1>Repair order journey</h1><p className="intro">Request a single current journey. Credentials are used only for this request.</p></header><form className="lookup-form" onSubmit={submit} noValidate><div className="field"><label htmlFor="vin">VIN</label><input id="vin" value={state.form.vin} onChange={(e) => dispatch({ type: "EDIT", field: "vin", value: e.target.value })} aria-required="true" aria-invalid={Boolean(state.errors.vin)} aria-describedby={state.errors.vin ? "vin-error" : undefined} autoComplete="off" />{state.errors.vin && <p id="vin-error" role="alert">{state.errors.vin}</p>}</div><div className="field"><label htmlFor="scenario">Scenario</label><select id="scenario" value={state.form.scenario} onChange={(e) => dispatch({ type: "EDIT", field: "scenario", value: e.target.value })}><option value="RO_OPEN">Repair order open</option><option value="RO_CLOSE">Repair order close</option></select></div><div className="field"><label htmlFor="environment">Environment</label><select id="environment" value={state.form.environment} onChange={(e) => dispatch({ type: "EDIT", field: "environment", value: e.target.value })} aria-required="true"><option value="test">Test</option><option value="stage">Stage</option><option value="prod">Production</option></select></div><div className="field"><label htmlFor="apiKey">API key</label><input id="apiKey" type="password" value={state.form.apiKey} onChange={(e) => dispatch({ type: "EDIT", field: "apiKey", value: e.target.value })} aria-required="true" aria-invalid={Boolean(state.errors.apiKey)} aria-describedby={state.errors.apiKey ? "api-key-error" : undefined} autoComplete="new-password" />{state.errors.apiKey && <p id="api-key-error" role="alert">{state.errors.apiKey}</p>}</div><div className="actions"><button className="secondary" type="button" onClick={() => dispatch({ type: "CLEAR" })} disabled={state.pending}>Clear</button><button type="submit" disabled={state.pending}>{state.pending ? "Looking up…" : "Look up journey"}</button></div><p className="security-note" aria-live="polite">{state.pending ? "Looking up…" : "The submitted key is cleared after each response."}</p></form></main>; };
